### ISSUE TITLE
Benchmark results

### ISSUE THREAD

**Issue by HaisongDing** [darianfrajberg/polimidl#1]
Could you share your benchmark results on popular neural networks or share your paper in https://link.springer.com/chapter/10.1007/978-3-030-23367-9_9. I have difficulties accessing this paper.

**Comment by darianfrajberg** [comment]
Hi HaisongDing,
You can find a preprint version of the paper in the following link:
https://re.public.polimi.it/retrieve/handle/11311/1090919/379224/Accelerating_Deep_Learning_inference_on_mobile_systems_preprint.pdf
